# add one configuration for each topic to remap
#
# name: node name for output/debug purposes
# input_topic: topic where to read from
# output_topic: topic where to forward remapped messages to
# message_type: ROS type of message to be remapped (Python syntax, e.g. "geometry_msgs.msg.Pose")
# message_field: field name if this is a nested message (e.g. "position" if you want to remap geometry_msgs.msg.Pose.position)
# values_in: combination of field name and value to be remapped
# values_out: combination of field name and value which should be output instead of the input value

configurations:
  -
    name: "demo_remap_pose"
    input_topic: "/demo_remap_pose_in"
    output_topic: "/demo_remap_pose_out"
    message_type: "geometry_msgs.msg.PoseStamped"
    message_field: "header"
    frequency: 10
    queue_size: 10
    values_in:
      frame_id: "frame_in"
    values_out:
      frame_id: "frame_out"
